# Generated by Django 3.1.7 on 2021-03-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReidImage',
            fields=[
                ('unicode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='reid')),
            ],
        ),
    ]
